# Generated by Django 2.0.5 on 2018-05-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineIndex',
            fields=[
                ('line_number', models.BigIntegerField(primary_key=True, serialize=False)),
                ('offset', models.BigIntegerField()),
            ],
            options={
                'ordering': ('line_number',),
            },
        ),
    ]
